In [5]:
import numpy as np

In [6]:
np.sqrt(25)

5.0

# Arrays

## np.array()

In [7]:
a = [0, 1, 2, 3, 4, 5]

type(a)

list

In [8]:
type(np.array(a))

numpy.ndarray

## np.arange()

In [9]:
b = np.arange(4, 24, 2)

print(b)

[ 4  6  8 10 12 14 16 18 20 22]


## np.linspace()

In [10]:
c = np.linspace(1, 244, 5)

c

array([  1.  ,  61.75, 122.5 , 183.25, 244.  ])

## np.zeros()

In [11]:
d = np.zeros(50)

d

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## np.ones()

In [12]:
e = np.ones(50)

e

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Dimensiones

In [13]:
array_2d = np.array([d, e])

In [14]:
print(array_2d)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1.]]


## array.shape

In [15]:
array_2d.shape

(2, 50)

## array.size

In [16]:
array_2d.size

100

## array.ndim

In [17]:
array_2d.ndim

2

## Operaciones con arrays

In [18]:
lista_1 = [1, 2, 3]
lista_2 = [4, 5, 6]

In [19]:
array_1 = np.array(lista_1)
array_2 = np.array(lista_2)

In [20]:
array_1 * array_2

array([ 4, 10, 18])

In [21]:
[ num1 * num2 for num1, num2 in zip(lista_1, lista_2)]

[4, 10, 18]

In [22]:
%%timeit
[ num1 * num2 for num1, num2 in zip(lista_1, lista_2)]

793 ns ± 57.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [23]:
%%timeit
array_1 * array_2

753 ns ± 41.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# Funciones

## np.reshape()

In [29]:
array_2d.size

100

In [30]:
f = np.reshape(array_2d, (10, 10))

In [31]:
f

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## array.T

In [34]:
a = np.array([[1, 2, 3, 4, 5], [10, 20, 30, 40, 50], [100, 200, 300, 400, 500]])

a

array([[  1,   2,   3,   4,   5],
       [ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500]])

In [35]:
a.T

array([[  1,  10, 100],
       [  2,  20, 200],
       [  3,  30, 300],
       [  4,  40, 400],
       [  5,  50, 500]])

## np.random

### np.random.randint

In [36]:
np.random.randint(1, 300)

185

## np.where

In [37]:
array_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.]])

In [38]:
np.where(array_2d == 1, array_2d * 10, array_2d - 5)

array([[-5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5.,
        -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5.,
        -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5.,
        -5., -5., -5., -5., -5., -5., -5., -5., -5., -5., -5.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]])

# Estadistica

## Distribuciones

In [39]:
array_normal = np.random.normal(1.75, 0.05, 1000)

In [40]:
array_normal

array([1.72901208, 1.69125065, 1.73197481, 1.72115755, 1.72467037,
       1.71663611, 1.7182595 , 1.76358003, 1.84908227, 1.70883473,
       1.82638767, 1.77496003, 1.7848792 , 1.71833256, 1.83634528,
       1.76626693, 1.74866932, 1.81414928, 1.83170458, 1.69429   ,
       1.75456677, 1.68520783, 1.75149067, 1.72937088, 1.75478264,
       1.86965268, 1.79276899, 1.77048827, 1.71966895, 1.92236794,
       1.77367826, 1.74545892, 1.72221227, 1.71959226, 1.66116029,
       1.75372636, 1.77922647, 1.81336374, 1.69035276, 1.76764185,
       1.77684346, 1.83078625, 1.76085761, 1.73415216, 1.73863442,
       1.76932357, 1.72556047, 1.83237467, 1.82689273, 1.7344065 ,
       1.8195141 , 1.69612512, 1.71035811, 1.69523169, 1.70331902,
       1.74274762, 1.83975144, 1.80787146, 1.73835679, 1.75082081,
       1.69375819, 1.71622036, 1.82832132, 1.8283626 , 1.74661892,
       1.77601321, 1.72132705, 1.76452865, 1.86694707, 1.75856931,
       1.78492822, 1.80324585, 1.87312205, 1.75909278, 1.83123

## np.mean

In [41]:
np.mean(array_normal)

1.750427165310333

## np.median

In [42]:
np.median(array_normal)

1.7498641091208191

## np.std

In [43]:
np.std(array_normal)

0.049432048272450804